import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import Main from "@/components/Main";
import "./globals.css";

export const metadata = {
  title: "Project Manager",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black text-gray-400 w-screen h-screen overflow-hidden">
        <div className="flex flex-col p-2">
          <Header />
          <div className="flex w-screen">
            <Sidebar />
            <Main>
              {children}
              </Main>
          </div>
        </div>
      </body>
    </html>
  );
}
