import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import Main from "@/components/Main";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"


export const metadata = {
  title: "Project Manager",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-950 text-gray-400 w-screen h-screen overflow-hidden">
        <div className="relative">
          {/* <Header /> */}
          <div className="flex w-screen">
            <Sidebar />
            <Main>
              {children}
              </Main>
          </div>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
